// Code generated by ent, DO NOT EDIT.

package usagelog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldID, id))
placeholder

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldID, id))
placeholder

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldID, id))
placeholder

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldID, ids...))
placeholder

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldID, ids...))
placeholder

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldID, id))
placeholder

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldID, id))
placeholder

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldID, id))
placeholder

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldID, id))
placeholder

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUserID, v))
placeholder

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldAPIKeyID, v))
placeholder

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldAccountID, v))
placeholder

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldRequestID, v))
placeholder

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldModel, v))
placeholder

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldGroupID, v))
placeholder

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldSubscriptionID, v))
placeholder

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputTokens, v))
placeholder

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputTokens, v))
placeholder

// CacheCreationTokens applies equality check predicate on the "cache_creation_tokens" field. It's identical to CacheCreationTokensEQ.
func CacheCreationTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreationTokens, v))
placeholder

// CacheReadTokens applies equality check predicate on the "cache_read_tokens" field. It's identical to CacheReadTokensEQ.
func CacheReadTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheReadTokens, v))
placeholder

// CacheCreation5mTokens applies equality check predicate on the "cache_creation_5m_tokens" field. It's identical to CacheCreation5mTokensEQ.
func CacheCreation5mTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreation5mTokens, v))
placeholder

// CacheCreation1hTokens applies equality check predicate on the "cache_creation_1h_tokens" field. It's identical to CacheCreation1hTokensEQ.
func CacheCreation1hTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreation1hTokens, v))
placeholder

// InputCost applies equality check predicate on the "input_cost" field. It's identical to InputCostEQ.
func InputCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputCost, v))
placeholder

// OutputCost applies equality check predicate on the "output_cost" field. It's identical to OutputCostEQ.
func OutputCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputCost, v))
placeholder

// CacheCreationCost applies equality check predicate on the "cache_creation_cost" field. It's identical to CacheCreationCostEQ.
func CacheCreationCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreationCost, v))
placeholder

// CacheReadCost applies equality check predicate on the "cache_read_cost" field. It's identical to CacheReadCostEQ.
func CacheReadCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheReadCost, v))
placeholder

// TotalCost applies equality check predicate on the "total_cost" field. It's identical to TotalCostEQ.
func TotalCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldTotalCost, v))
placeholder

// ActualCost applies equality check predicate on the "actual_cost" field. It's identical to ActualCostEQ.
func ActualCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldActualCost, v))
placeholder

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldRateMultiplier, v))
placeholder

// BillingType applies equality check predicate on the "billing_type" field. It's identical to BillingTypeEQ.
func BillingType(v int8) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldBillingType, v))
placeholder

// Stream applies equality check predicate on the "stream" field. It's identical to StreamEQ.
func Stream(v bool) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldStream, v))
placeholder

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldDurationMs, v))
placeholder

// FirstTokenMs applies equality check predicate on the "first_token_ms" field. It's identical to FirstTokenMsEQ.
func FirstTokenMs(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldFirstTokenMs, v))
placeholder

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUserAgent, v))
placeholder

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldIPAddress, v))
placeholder

// ImageCount applies equality check predicate on the "image_count" field. It's identical to ImageCountEQ.
func ImageCount(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldImageCount, v))
placeholder

// ImageSize applies equality check predicate on the "image_size" field. It's identical to ImageSizeEQ.
func ImageSize(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldImageSize, v))
placeholder

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCreatedAt, v))
placeholder

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUserID, v))
placeholder

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldUserID, v))
placeholder

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldUserID, vs...))
placeholder

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldUserID, vs...))
placeholder

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldAPIKeyID, v))
placeholder

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldAPIKeyID, v))
placeholder

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldAPIKeyID, vs...))
placeholder

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldAPIKeyID, vs...))
placeholder

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldAccountID, v))
placeholder

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldAccountID, v))
placeholder

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldAccountID, vs...))
placeholder

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldAccountID, vs...))
placeholder

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldRequestID, v))
placeholder

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldRequestID, v))
placeholder

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldRequestID, vs...))
placeholder

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldRequestID, vs...))
placeholder

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldRequestID, v))
placeholder

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldRequestID, v))
placeholder

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldRequestID, v))
placeholder

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldRequestID, v))
placeholder

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldRequestID, v))
placeholder

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldRequestID, v))
placeholder

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldRequestID, v))
placeholder

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldRequestID, v))
placeholder

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldRequestID, v))
placeholder

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldModel, v))
placeholder

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldModel, v))
placeholder

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldModel, vs...))
placeholder

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldModel, vs...))
placeholder

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldModel, v))
placeholder

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldModel, v))
placeholder

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldModel, v))
placeholder

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldModel, v))
placeholder

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldModel, v))
placeholder

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldModel, v))
placeholder

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldModel, v))
placeholder

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldModel, v))
placeholder

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldModel, v))
placeholder

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldGroupID, v))
placeholder

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldGroupID, v))
placeholder

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldGroupID, vs...))
placeholder

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldGroupID, vs...))
placeholder

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldGroupID))
placeholder

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldGroupID))
placeholder

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldSubscriptionID, v))
placeholder

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldSubscriptionID, v))
placeholder

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldSubscriptionID, vs...))
placeholder

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldSubscriptionID, vs...))
placeholder

// SubscriptionIDIsNil applies the IsNil predicate on the "subscription_id" field.
func SubscriptionIDIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldSubscriptionID))
placeholder

// SubscriptionIDNotNil applies the NotNil predicate on the "subscription_id" field.
func SubscriptionIDNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldSubscriptionID))
placeholder

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputTokens, v))
placeholder

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldInputTokens, v))
placeholder

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldInputTokens, vs...))
placeholder

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldInputTokens, vs...))
placeholder

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldInputTokens, v))
placeholder

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldInputTokens, v))
placeholder

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldInputTokens, v))
placeholder

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldInputTokens, v))
placeholder

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputTokens, v))
placeholder

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldOutputTokens, v))
placeholder

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldOutputTokens, vs...))
placeholder

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldOutputTokens, vs...))
placeholder

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldOutputTokens, v))
placeholder

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldOutputTokens, v))
placeholder

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldOutputTokens, v))
placeholder

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldOutputTokens, v))
placeholder

// CacheCreationTokensEQ applies the EQ predicate on the "cache_creation_tokens" field.
func CacheCreationTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreationTokens, v))
placeholder

// CacheCreationTokensNEQ applies the NEQ predicate on the "cache_creation_tokens" field.
func CacheCreationTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCacheCreationTokens, v))
placeholder

// CacheCreationTokensIn applies the In predicate on the "cache_creation_tokens" field.
func CacheCreationTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCacheCreationTokens, vs...))
placeholder

// CacheCreationTokensNotIn applies the NotIn predicate on the "cache_creation_tokens" field.
func CacheCreationTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCacheCreationTokens, vs...))
placeholder

// CacheCreationTokensGT applies the GT predicate on the "cache_creation_tokens" field.
func CacheCreationTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCacheCreationTokens, v))
placeholder

// CacheCreationTokensGTE applies the GTE predicate on the "cache_creation_tokens" field.
func CacheCreationTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCacheCreationTokens, v))
placeholder

// CacheCreationTokensLT applies the LT predicate on the "cache_creation_tokens" field.
func CacheCreationTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCacheCreationTokens, v))
placeholder

// CacheCreationTokensLTE applies the LTE predicate on the "cache_creation_tokens" field.
func CacheCreationTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCacheCreationTokens, v))
placeholder

// CacheReadTokensEQ applies the EQ predicate on the "cache_read_tokens" field.
func CacheReadTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheReadTokens, v))
placeholder

// CacheReadTokensNEQ applies the NEQ predicate on the "cache_read_tokens" field.
func CacheReadTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCacheReadTokens, v))
placeholder

// CacheReadTokensIn applies the In predicate on the "cache_read_tokens" field.
func CacheReadTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCacheReadTokens, vs...))
placeholder

// CacheReadTokensNotIn applies the NotIn predicate on the "cache_read_tokens" field.
func CacheReadTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCacheReadTokens, vs...))
placeholder

// CacheReadTokensGT applies the GT predicate on the "cache_read_tokens" field.
func CacheReadTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCacheReadTokens, v))
placeholder

// CacheReadTokensGTE applies the GTE predicate on the "cache_read_tokens" field.
func CacheReadTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCacheReadTokens, v))
placeholder

// CacheReadTokensLT applies the LT predicate on the "cache_read_tokens" field.
func CacheReadTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCacheReadTokens, v))
placeholder

// CacheReadTokensLTE applies the LTE predicate on the "cache_read_tokens" field.
func CacheReadTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCacheReadTokens, v))
placeholder

// CacheCreation5mTokensEQ applies the EQ predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreation5mTokens, v))
placeholder

// CacheCreation5mTokensNEQ applies the NEQ predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCacheCreation5mTokens, v))
placeholder

// CacheCreation5mTokensIn applies the In predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCacheCreation5mTokens, vs...))
placeholder

// CacheCreation5mTokensNotIn applies the NotIn predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCacheCreation5mTokens, vs...))
placeholder

// CacheCreation5mTokensGT applies the GT predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCacheCreation5mTokens, v))
placeholder

// CacheCreation5mTokensGTE applies the GTE predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCacheCreation5mTokens, v))
placeholder

// CacheCreation5mTokensLT applies the LT predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCacheCreation5mTokens, v))
placeholder

// CacheCreation5mTokensLTE applies the LTE predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCacheCreation5mTokens, v))
placeholder

// CacheCreation1hTokensEQ applies the EQ predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreation1hTokens, v))
placeholder

// CacheCreation1hTokensNEQ applies the NEQ predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCacheCreation1hTokens, v))
placeholder

// CacheCreation1hTokensIn applies the In predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCacheCreation1hTokens, vs...))
placeholder

// CacheCreation1hTokensNotIn applies the NotIn predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCacheCreation1hTokens, vs...))
placeholder

// CacheCreation1hTokensGT applies the GT predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCacheCreation1hTokens, v))
placeholder

// CacheCreation1hTokensGTE applies the GTE predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCacheCreation1hTokens, v))
placeholder

// CacheCreation1hTokensLT applies the LT predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCacheCreation1hTokens, v))
placeholder

// CacheCreation1hTokensLTE applies the LTE predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCacheCreation1hTokens, v))
placeholder

// InputCostEQ applies the EQ predicate on the "input_cost" field.
func InputCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputCost, v))
placeholder

// InputCostNEQ applies the NEQ predicate on the "input_cost" field.
func InputCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldInputCost, v))
placeholder

// InputCostIn applies the In predicate on the "input_cost" field.
func InputCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldInputCost, vs...))
placeholder

// InputCostNotIn applies the NotIn predicate on the "input_cost" field.
func InputCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldInputCost, vs...))
placeholder

// InputCostGT applies the GT predicate on the "input_cost" field.
func InputCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldInputCost, v))
placeholder

// InputCostGTE applies the GTE predicate on the "input_cost" field.
func InputCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldInputCost, v))
placeholder

// InputCostLT applies the LT predicate on the "input_cost" field.
func InputCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldInputCost, v))
placeholder

// InputCostLTE applies the LTE predicate on the "input_cost" field.
func InputCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldInputCost, v))
placeholder

// OutputCostEQ applies the EQ predicate on the "output_cost" field.
func OutputCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputCost, v))
placeholder

// OutputCostNEQ applies the NEQ predicate on the "output_cost" field.
func OutputCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldOutputCost, v))
placeholder

// OutputCostIn applies the In predicate on the "output_cost" field.
func OutputCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldOutputCost, vs...))
placeholder

// OutputCostNotIn applies the NotIn predicate on the "output_cost" field.
func OutputCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldOutputCost, vs...))
placeholder

// OutputCostGT applies the GT predicate on the "output_cost" field.
func OutputCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldOutputCost, v))
placeholder

// OutputCostGTE applies the GTE predicate on the "output_cost" field.
func OutputCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldOutputCost, v))
placeholder

// OutputCostLT applies the LT predicate on the "output_cost" field.
func OutputCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldOutputCost, v))
placeholder

// OutputCostLTE applies the LTE predicate on the "output_cost" field.
func OutputCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldOutputCost, v))
placeholder

// CacheCreationCostEQ applies the EQ predicate on the "cache_creation_cost" field.
func CacheCreationCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreationCost, v))
placeholder

// CacheCreationCostNEQ applies the NEQ predicate on the "cache_creation_cost" field.
func CacheCreationCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCacheCreationCost, v))
placeholder

// CacheCreationCostIn applies the In predicate on the "cache_creation_cost" field.
func CacheCreationCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCacheCreationCost, vs...))
placeholder

// CacheCreationCostNotIn applies the NotIn predicate on the "cache_creation_cost" field.
func CacheCreationCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCacheCreationCost, vs...))
placeholder

// CacheCreationCostGT applies the GT predicate on the "cache_creation_cost" field.
func CacheCreationCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCacheCreationCost, v))
placeholder

// CacheCreationCostGTE applies the GTE predicate on the "cache_creation_cost" field.
func CacheCreationCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCacheCreationCost, v))
placeholder

// CacheCreationCostLT applies the LT predicate on the "cache_creation_cost" field.
func CacheCreationCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCacheCreationCost, v))
placeholder

// CacheCreationCostLTE applies the LTE predicate on the "cache_creation_cost" field.
func CacheCreationCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCacheCreationCost, v))
placeholder

// CacheReadCostEQ applies the EQ predicate on the "cache_read_cost" field.
func CacheReadCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheReadCost, v))
placeholder

// CacheReadCostNEQ applies the NEQ predicate on the "cache_read_cost" field.
func CacheReadCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCacheReadCost, v))
placeholder

// CacheReadCostIn applies the In predicate on the "cache_read_cost" field.
func CacheReadCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCacheReadCost, vs...))
placeholder

// CacheReadCostNotIn applies the NotIn predicate on the "cache_read_cost" field.
func CacheReadCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCacheReadCost, vs...))
placeholder

// CacheReadCostGT applies the GT predicate on the "cache_read_cost" field.
func CacheReadCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCacheReadCost, v))
placeholder

// CacheReadCostGTE applies the GTE predicate on the "cache_read_cost" field.
func CacheReadCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCacheReadCost, v))
placeholder

// CacheReadCostLT applies the LT predicate on the "cache_read_cost" field.
func CacheReadCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCacheReadCost, v))
placeholder

// CacheReadCostLTE applies the LTE predicate on the "cache_read_cost" field.
func CacheReadCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCacheReadCost, v))
placeholder

// TotalCostEQ applies the EQ predicate on the "total_cost" field.
func TotalCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldTotalCost, v))
placeholder

// TotalCostNEQ applies the NEQ predicate on the "total_cost" field.
func TotalCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldTotalCost, v))
placeholder

// TotalCostIn applies the In predicate on the "total_cost" field.
func TotalCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldTotalCost, vs...))
placeholder

// TotalCostNotIn applies the NotIn predicate on the "total_cost" field.
func TotalCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldTotalCost, vs...))
placeholder

// TotalCostGT applies the GT predicate on the "total_cost" field.
func TotalCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldTotalCost, v))
placeholder

// TotalCostGTE applies the GTE predicate on the "total_cost" field.
func TotalCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldTotalCost, v))
placeholder

// TotalCostLT applies the LT predicate on the "total_cost" field.
func TotalCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldTotalCost, v))
placeholder

// TotalCostLTE applies the LTE predicate on the "total_cost" field.
func TotalCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldTotalCost, v))
placeholder

// ActualCostEQ applies the EQ predicate on the "actual_cost" field.
func ActualCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldActualCost, v))
placeholder

// ActualCostNEQ applies the NEQ predicate on the "actual_cost" field.
func ActualCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldActualCost, v))
placeholder

// ActualCostIn applies the In predicate on the "actual_cost" field.
func ActualCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldActualCost, vs...))
placeholder

// ActualCostNotIn applies the NotIn predicate on the "actual_cost" field.
func ActualCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldActualCost, vs...))
placeholder

// ActualCostGT applies the GT predicate on the "actual_cost" field.
func ActualCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldActualCost, v))
placeholder

// ActualCostGTE applies the GTE predicate on the "actual_cost" field.
func ActualCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldActualCost, v))
placeholder

// ActualCostLT applies the LT predicate on the "actual_cost" field.
func ActualCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldActualCost, v))
placeholder

// ActualCostLTE applies the LTE predicate on the "actual_cost" field.
func ActualCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldActualCost, v))
placeholder

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldRateMultiplier, v))
placeholder

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldRateMultiplier, v))
placeholder

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldRateMultiplier, vs...))
placeholder

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldRateMultiplier, vs...))
placeholder

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldRateMultiplier, v))
placeholder

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldRateMultiplier, v))
placeholder

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldRateMultiplier, v))
placeholder

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldRateMultiplier, v))
placeholder

// BillingTypeEQ applies the EQ predicate on the "billing_type" field.
func BillingTypeEQ(v int8) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldBillingType, v))
placeholder

// BillingTypeNEQ applies the NEQ predicate on the "billing_type" field.
func BillingTypeNEQ(v int8) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldBillingType, v))
placeholder

// BillingTypeIn applies the In predicate on the "billing_type" field.
func BillingTypeIn(vs ...int8) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldBillingType, vs...))
placeholder

// BillingTypeNotIn applies the NotIn predicate on the "billing_type" field.
func BillingTypeNotIn(vs ...int8) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldBillingType, vs...))
placeholder

// BillingTypeGT applies the GT predicate on the "billing_type" field.
func BillingTypeGT(v int8) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldBillingType, v))
placeholder

// BillingTypeGTE applies the GTE predicate on the "billing_type" field.
func BillingTypeGTE(v int8) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldBillingType, v))
placeholder

// BillingTypeLT applies the LT predicate on the "billing_type" field.
func BillingTypeLT(v int8) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldBillingType, v))
placeholder

// BillingTypeLTE applies the LTE predicate on the "billing_type" field.
func BillingTypeLTE(v int8) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldBillingType, v))
placeholder

// StreamEQ applies the EQ predicate on the "stream" field.
func StreamEQ(v bool) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldStream, v))
placeholder

// StreamNEQ applies the NEQ predicate on the "stream" field.
func StreamNEQ(v bool) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldStream, v))
placeholder

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldDurationMs, v))
placeholder

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldDurationMs, v))
placeholder

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldDurationMs, vs...))
placeholder

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldDurationMs, vs...))
placeholder

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldDurationMs, v))
placeholder

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldDurationMs, v))
placeholder

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldDurationMs, v))
placeholder

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldDurationMs, v))
placeholder

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldDurationMs))
placeholder

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldDurationMs))
placeholder

// FirstTokenMsEQ applies the EQ predicate on the "first_token_ms" field.
func FirstTokenMsEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldFirstTokenMs, v))
placeholder

// FirstTokenMsNEQ applies the NEQ predicate on the "first_token_ms" field.
func FirstTokenMsNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldFirstTokenMs, v))
placeholder

// FirstTokenMsIn applies the In predicate on the "first_token_ms" field.
func FirstTokenMsIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldFirstTokenMs, vs...))
placeholder

// FirstTokenMsNotIn applies the NotIn predicate on the "first_token_ms" field.
func FirstTokenMsNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldFirstTokenMs, vs...))
placeholder

// FirstTokenMsGT applies the GT predicate on the "first_token_ms" field.
func FirstTokenMsGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldFirstTokenMs, v))
placeholder

// FirstTokenMsGTE applies the GTE predicate on the "first_token_ms" field.
func FirstTokenMsGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldFirstTokenMs, v))
placeholder

// FirstTokenMsLT applies the LT predicate on the "first_token_ms" field.
func FirstTokenMsLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldFirstTokenMs, v))
placeholder

// FirstTokenMsLTE applies the LTE predicate on the "first_token_ms" field.
func FirstTokenMsLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldFirstTokenMs, v))
placeholder

// FirstTokenMsIsNil applies the IsNil predicate on the "first_token_ms" field.
func FirstTokenMsIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldFirstTokenMs))
placeholder

// FirstTokenMsNotNil applies the NotNil predicate on the "first_token_ms" field.
func FirstTokenMsNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldFirstTokenMs))
placeholder

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUserAgent, v))
placeholder

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldUserAgent, v))
placeholder

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldUserAgent, vs...))
placeholder

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldUserAgent, vs...))
placeholder

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldUserAgent, v))
placeholder

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldUserAgent, v))
placeholder

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldUserAgent, v))
placeholder

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldUserAgent, v))
placeholder

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldUserAgent, v))
placeholder

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldUserAgent, v))
placeholder

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldUserAgent, v))
placeholder

// UserAgentIsNil applies the IsNil predicate on the "user_agent" field.
func UserAgentIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldUserAgent))
placeholder

// UserAgentNotNil applies the NotNil predicate on the "user_agent" field.
func UserAgentNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldUserAgent))
placeholder

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldUserAgent, v))
placeholder

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldUserAgent, v))
placeholder

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldIPAddress, v))
placeholder

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldIPAddress, v))
placeholder

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldIPAddress, vs...))
placeholder

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldIPAddress, vs...))
placeholder

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldIPAddress, v))
placeholder

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldIPAddress, v))
placeholder

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldIPAddress, v))
placeholder

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldIPAddress, v))
placeholder

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldIPAddress, v))
placeholder

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldIPAddress, v))
placeholder

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldIPAddress, v))
placeholder

// IPAddressIsNil applies the IsNil predicate on the "ip_address" field.
func IPAddressIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldIPAddress))
placeholder

// IPAddressNotNil applies the NotNil predicate on the "ip_address" field.
func IPAddressNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldIPAddress))
placeholder

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldIPAddress, v))
placeholder

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldIPAddress, v))
placeholder

// ImageCountEQ applies the EQ predicate on the "image_count" field.
func ImageCountEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldImageCount, v))
placeholder

// ImageCountNEQ applies the NEQ predicate on the "image_count" field.
func ImageCountNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldImageCount, v))
placeholder

// ImageCountIn applies the In predicate on the "image_count" field.
func ImageCountIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldImageCount, vs...))
placeholder

// ImageCountNotIn applies the NotIn predicate on the "image_count" field.
func ImageCountNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldImageCount, vs...))
placeholder

// ImageCountGT applies the GT predicate on the "image_count" field.
func ImageCountGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldImageCount, v))
placeholder

// ImageCountGTE applies the GTE predicate on the "image_count" field.
func ImageCountGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldImageCount, v))
placeholder

// ImageCountLT applies the LT predicate on the "image_count" field.
func ImageCountLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldImageCount, v))
placeholder

// ImageCountLTE applies the LTE predicate on the "image_count" field.
func ImageCountLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldImageCount, v))
placeholder

// ImageSizeEQ applies the EQ predicate on the "image_size" field.
func ImageSizeEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldImageSize, v))
placeholder

// ImageSizeNEQ applies the NEQ predicate on the "image_size" field.
func ImageSizeNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldImageSize, v))
placeholder

// ImageSizeIn applies the In predicate on the "image_size" field.
func ImageSizeIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldImageSize, vs...))
placeholder

// ImageSizeNotIn applies the NotIn predicate on the "image_size" field.
func ImageSizeNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldImageSize, vs...))
placeholder

// ImageSizeGT applies the GT predicate on the "image_size" field.
func ImageSizeGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldImageSize, v))
placeholder

// ImageSizeGTE applies the GTE predicate on the "image_size" field.
func ImageSizeGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldImageSize, v))
placeholder

// ImageSizeLT applies the LT predicate on the "image_size" field.
func ImageSizeLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldImageSize, v))
placeholder

// ImageSizeLTE applies the LTE predicate on the "image_size" field.
func ImageSizeLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldImageSize, v))
placeholder

// ImageSizeContains applies the Contains predicate on the "image_size" field.
func ImageSizeContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldImageSize, v))
placeholder

// ImageSizeHasPrefix applies the HasPrefix predicate on the "image_size" field.
func ImageSizeHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldImageSize, v))
placeholder

// ImageSizeHasSuffix applies the HasSuffix predicate on the "image_size" field.
func ImageSizeHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldImageSize, v))
placeholder

// ImageSizeIsNil applies the IsNil predicate on the "image_size" field.
func ImageSizeIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldImageSize))
placeholder

// ImageSizeNotNil applies the NotNil predicate on the "image_size" field.
func ImageSizeNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldImageSize))
placeholder

// ImageSizeEqualFold applies the EqualFold predicate on the "image_size" field.
func ImageSizeEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldImageSize, v))
placeholder

// ImageSizeContainsFold applies the ContainsFold predicate on the "image_size" field.
func ImageSizeContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldImageSize, v))
placeholder

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCreatedAt, v))
placeholder

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCreatedAt, v))
placeholder

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCreatedAt, vs...))
placeholder

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCreatedAt, vs...))
placeholder

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCreatedAt, v))
placeholder

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCreatedAt, v))
placeholder

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCreatedAt, v))
placeholder

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCreatedAt, v))
placeholder

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
placeholder)
placeholder

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
		placeholder
	placeholder)
placeholder)
placeholder

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
placeholder)
placeholder

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
		placeholder
	placeholder)
placeholder)
placeholder

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
placeholder)
placeholder

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
		placeholder
	placeholder)
placeholder)
placeholder

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
placeholder)
placeholder

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
		placeholder
	placeholder)
placeholder)
placeholder

// HasSubscription applies the HasEdge predicate on the "subscription" edge.
func HasSubscription() predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionTable, SubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
placeholder)
placeholder

// HasSubscriptionWith applies the HasEdge predicate on the "subscription" edge with a given conditions (other predicates).
func HasSubscriptionWith(preds ...predicate.UserSubscription) predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := newSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
		placeholder
	placeholder)
placeholder)
placeholder

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageLog) predicate.UsageLog {
	return predicate.UsageLog(sql.AndPredicates(predicates...))
placeholder

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageLog) predicate.UsageLog {
	return predicate.UsageLog(sql.OrPredicates(predicates...))
placeholder

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageLog) predicate.UsageLog {
	return predicate.UsageLog(sql.NotPredicates(p))
placeholder
