// Code generated by ent, DO NOT EDIT.

package batchimageitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldID, id))
placeholder

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldID, id))
placeholder

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldID, id))
placeholder

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldID, ids...))
placeholder

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldID, ids...))
placeholder

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldID, id))
placeholder

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldID, id))
placeholder

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldID, id))
placeholder

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldID, id))
placeholder

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldJobID, v))
placeholder

// CustomID applies equality check predicate on the "custom_id" field. It's identical to CustomIDEQ.
func CustomID(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldCustomID, v))
placeholder

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldStatus, v))
placeholder

// RequestHash applies equality check predicate on the "request_hash" field. It's identical to RequestHashEQ.
func RequestHash(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldRequestHash, v))
placeholder

// PromptPreview applies equality check predicate on the "prompt_preview" field. It's identical to PromptPreviewEQ.
func PromptPreview(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldPromptPreview, v))
placeholder

// ProviderSourceObject applies equality check predicate on the "provider_source_object" field. It's identical to ProviderSourceObjectEQ.
func ProviderSourceObject(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldProviderSourceObject, v))
placeholder

// SourceLineNumber applies equality check predicate on the "source_line_number" field. It's identical to SourceLineNumberEQ.
func SourceLineNumber(v int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldSourceLineNumber, v))
placeholder

// SourceByteOffset applies equality check predicate on the "source_byte_offset" field. It's identical to SourceByteOffsetEQ.
func SourceByteOffset(v int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldSourceByteOffset, v))
placeholder

// SourceByteLength applies equality check predicate on the "source_byte_length" field. It's identical to SourceByteLengthEQ.
func SourceByteLength(v int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldSourceByteLength, v))
placeholder

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldMimeType, v))
placeholder

// FileExtension applies equality check predicate on the "file_extension" field. It's identical to FileExtensionEQ.
func FileExtension(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldFileExtension, v))
placeholder

// ImageCount applies equality check predicate on the "image_count" field. It's identical to ImageCountEQ.
func ImageCount(v int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldImageCount, v))
placeholder

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldErrorCode, v))
placeholder

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldErrorMessage, v))
placeholder

// BilledAmount applies equality check predicate on the "billed_amount" field. It's identical to BilledAmountEQ.
func BilledAmount(v float64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldBilledAmount, v))
placeholder

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldCreatedAt, v))
placeholder

// IndexedAt applies equality check predicate on the "indexed_at" field. It's identical to IndexedAtEQ.
func IndexedAt(v time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldIndexedAt, v))
placeholder

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldJobID, v))
placeholder

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldJobID, v))
placeholder

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldJobID, vs...))
placeholder

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldJobID, vs...))
placeholder

// JobIDGT applies the GT predicate on the "job_id" field.
func JobIDGT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldJobID, v))
placeholder

// JobIDGTE applies the GTE predicate on the "job_id" field.
func JobIDGTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldJobID, v))
placeholder

// JobIDLT applies the LT predicate on the "job_id" field.
func JobIDLT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldJobID, v))
placeholder

// JobIDLTE applies the LTE predicate on the "job_id" field.
func JobIDLTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldJobID, v))
placeholder

// JobIDContains applies the Contains predicate on the "job_id" field.
func JobIDContains(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContains(FieldJobID, v))
placeholder

// JobIDHasPrefix applies the HasPrefix predicate on the "job_id" field.
func JobIDHasPrefix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasPrefix(FieldJobID, v))
placeholder

// JobIDHasSuffix applies the HasSuffix predicate on the "job_id" field.
func JobIDHasSuffix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasSuffix(FieldJobID, v))
placeholder

// JobIDEqualFold applies the EqualFold predicate on the "job_id" field.
func JobIDEqualFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEqualFold(FieldJobID, v))
placeholder

// JobIDContainsFold applies the ContainsFold predicate on the "job_id" field.
func JobIDContainsFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContainsFold(FieldJobID, v))
placeholder

// CustomIDEQ applies the EQ predicate on the "custom_id" field.
func CustomIDEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldCustomID, v))
placeholder

// CustomIDNEQ applies the NEQ predicate on the "custom_id" field.
func CustomIDNEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldCustomID, v))
placeholder

// CustomIDIn applies the In predicate on the "custom_id" field.
func CustomIDIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldCustomID, vs...))
placeholder

// CustomIDNotIn applies the NotIn predicate on the "custom_id" field.
func CustomIDNotIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldCustomID, vs...))
placeholder

// CustomIDGT applies the GT predicate on the "custom_id" field.
func CustomIDGT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldCustomID, v))
placeholder

// CustomIDGTE applies the GTE predicate on the "custom_id" field.
func CustomIDGTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldCustomID, v))
placeholder

// CustomIDLT applies the LT predicate on the "custom_id" field.
func CustomIDLT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldCustomID, v))
placeholder

// CustomIDLTE applies the LTE predicate on the "custom_id" field.
func CustomIDLTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldCustomID, v))
placeholder

// CustomIDContains applies the Contains predicate on the "custom_id" field.
func CustomIDContains(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContains(FieldCustomID, v))
placeholder

// CustomIDHasPrefix applies the HasPrefix predicate on the "custom_id" field.
func CustomIDHasPrefix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasPrefix(FieldCustomID, v))
placeholder

// CustomIDHasSuffix applies the HasSuffix predicate on the "custom_id" field.
func CustomIDHasSuffix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasSuffix(FieldCustomID, v))
placeholder

// CustomIDEqualFold applies the EqualFold predicate on the "custom_id" field.
func CustomIDEqualFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEqualFold(FieldCustomID, v))
placeholder

// CustomIDContainsFold applies the ContainsFold predicate on the "custom_id" field.
func CustomIDContainsFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContainsFold(FieldCustomID, v))
placeholder

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldStatus, v))
placeholder

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldStatus, v))
placeholder

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldStatus, vs...))
placeholder

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldStatus, vs...))
placeholder

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldStatus, v))
placeholder

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldStatus, v))
placeholder

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldStatus, v))
placeholder

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldStatus, v))
placeholder

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContains(FieldStatus, v))
placeholder

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasPrefix(FieldStatus, v))
placeholder

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasSuffix(FieldStatus, v))
placeholder

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEqualFold(FieldStatus, v))
placeholder

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContainsFold(FieldStatus, v))
placeholder

// RequestHashEQ applies the EQ predicate on the "request_hash" field.
func RequestHashEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldRequestHash, v))
placeholder

// RequestHashNEQ applies the NEQ predicate on the "request_hash" field.
func RequestHashNEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldRequestHash, v))
placeholder

// RequestHashIn applies the In predicate on the "request_hash" field.
func RequestHashIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldRequestHash, vs...))
placeholder

// RequestHashNotIn applies the NotIn predicate on the "request_hash" field.
func RequestHashNotIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldRequestHash, vs...))
placeholder

// RequestHashGT applies the GT predicate on the "request_hash" field.
func RequestHashGT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldRequestHash, v))
placeholder

// RequestHashGTE applies the GTE predicate on the "request_hash" field.
func RequestHashGTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldRequestHash, v))
placeholder

// RequestHashLT applies the LT predicate on the "request_hash" field.
func RequestHashLT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldRequestHash, v))
placeholder

// RequestHashLTE applies the LTE predicate on the "request_hash" field.
func RequestHashLTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldRequestHash, v))
placeholder

// RequestHashContains applies the Contains predicate on the "request_hash" field.
func RequestHashContains(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContains(FieldRequestHash, v))
placeholder

// RequestHashHasPrefix applies the HasPrefix predicate on the "request_hash" field.
func RequestHashHasPrefix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasPrefix(FieldRequestHash, v))
placeholder

// RequestHashHasSuffix applies the HasSuffix predicate on the "request_hash" field.
func RequestHashHasSuffix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasSuffix(FieldRequestHash, v))
placeholder

// RequestHashIsNil applies the IsNil predicate on the "request_hash" field.
func RequestHashIsNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIsNull(FieldRequestHash))
placeholder

// RequestHashNotNil applies the NotNil predicate on the "request_hash" field.
func RequestHashNotNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotNull(FieldRequestHash))
placeholder

// RequestHashEqualFold applies the EqualFold predicate on the "request_hash" field.
func RequestHashEqualFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEqualFold(FieldRequestHash, v))
placeholder

// RequestHashContainsFold applies the ContainsFold predicate on the "request_hash" field.
func RequestHashContainsFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContainsFold(FieldRequestHash, v))
placeholder

// PromptPreviewEQ applies the EQ predicate on the "prompt_preview" field.
func PromptPreviewEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldPromptPreview, v))
placeholder

// PromptPreviewNEQ applies the NEQ predicate on the "prompt_preview" field.
func PromptPreviewNEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldPromptPreview, v))
placeholder

// PromptPreviewIn applies the In predicate on the "prompt_preview" field.
func PromptPreviewIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldPromptPreview, vs...))
placeholder

// PromptPreviewNotIn applies the NotIn predicate on the "prompt_preview" field.
func PromptPreviewNotIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldPromptPreview, vs...))
placeholder

// PromptPreviewGT applies the GT predicate on the "prompt_preview" field.
func PromptPreviewGT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldPromptPreview, v))
placeholder

// PromptPreviewGTE applies the GTE predicate on the "prompt_preview" field.
func PromptPreviewGTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldPromptPreview, v))
placeholder

// PromptPreviewLT applies the LT predicate on the "prompt_preview" field.
func PromptPreviewLT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldPromptPreview, v))
placeholder

// PromptPreviewLTE applies the LTE predicate on the "prompt_preview" field.
func PromptPreviewLTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldPromptPreview, v))
placeholder

// PromptPreviewContains applies the Contains predicate on the "prompt_preview" field.
func PromptPreviewContains(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContains(FieldPromptPreview, v))
placeholder

// PromptPreviewHasPrefix applies the HasPrefix predicate on the "prompt_preview" field.
func PromptPreviewHasPrefix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasPrefix(FieldPromptPreview, v))
placeholder

// PromptPreviewHasSuffix applies the HasSuffix predicate on the "prompt_preview" field.
func PromptPreviewHasSuffix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasSuffix(FieldPromptPreview, v))
placeholder

// PromptPreviewIsNil applies the IsNil predicate on the "prompt_preview" field.
func PromptPreviewIsNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIsNull(FieldPromptPreview))
placeholder

// PromptPreviewNotNil applies the NotNil predicate on the "prompt_preview" field.
func PromptPreviewNotNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotNull(FieldPromptPreview))
placeholder

// PromptPreviewEqualFold applies the EqualFold predicate on the "prompt_preview" field.
func PromptPreviewEqualFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEqualFold(FieldPromptPreview, v))
placeholder

// PromptPreviewContainsFold applies the ContainsFold predicate on the "prompt_preview" field.
func PromptPreviewContainsFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContainsFold(FieldPromptPreview, v))
placeholder

// ProviderSourceObjectEQ applies the EQ predicate on the "provider_source_object" field.
func ProviderSourceObjectEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldProviderSourceObject, v))
placeholder

// ProviderSourceObjectNEQ applies the NEQ predicate on the "provider_source_object" field.
func ProviderSourceObjectNEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldProviderSourceObject, v))
placeholder

// ProviderSourceObjectIn applies the In predicate on the "provider_source_object" field.
func ProviderSourceObjectIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldProviderSourceObject, vs...))
placeholder

// ProviderSourceObjectNotIn applies the NotIn predicate on the "provider_source_object" field.
func ProviderSourceObjectNotIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldProviderSourceObject, vs...))
placeholder

// ProviderSourceObjectGT applies the GT predicate on the "provider_source_object" field.
func ProviderSourceObjectGT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldProviderSourceObject, v))
placeholder

// ProviderSourceObjectGTE applies the GTE predicate on the "provider_source_object" field.
func ProviderSourceObjectGTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldProviderSourceObject, v))
placeholder

// ProviderSourceObjectLT applies the LT predicate on the "provider_source_object" field.
func ProviderSourceObjectLT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldProviderSourceObject, v))
placeholder

// ProviderSourceObjectLTE applies the LTE predicate on the "provider_source_object" field.
func ProviderSourceObjectLTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldProviderSourceObject, v))
placeholder

// ProviderSourceObjectContains applies the Contains predicate on the "provider_source_object" field.
func ProviderSourceObjectContains(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContains(FieldProviderSourceObject, v))
placeholder

// ProviderSourceObjectHasPrefix applies the HasPrefix predicate on the "provider_source_object" field.
func ProviderSourceObjectHasPrefix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasPrefix(FieldProviderSourceObject, v))
placeholder

// ProviderSourceObjectHasSuffix applies the HasSuffix predicate on the "provider_source_object" field.
func ProviderSourceObjectHasSuffix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasSuffix(FieldProviderSourceObject, v))
placeholder

// ProviderSourceObjectIsNil applies the IsNil predicate on the "provider_source_object" field.
func ProviderSourceObjectIsNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIsNull(FieldProviderSourceObject))
placeholder

// ProviderSourceObjectNotNil applies the NotNil predicate on the "provider_source_object" field.
func ProviderSourceObjectNotNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotNull(FieldProviderSourceObject))
placeholder

// ProviderSourceObjectEqualFold applies the EqualFold predicate on the "provider_source_object" field.
func ProviderSourceObjectEqualFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEqualFold(FieldProviderSourceObject, v))
placeholder

// ProviderSourceObjectContainsFold applies the ContainsFold predicate on the "provider_source_object" field.
func ProviderSourceObjectContainsFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContainsFold(FieldProviderSourceObject, v))
placeholder

// SourceLineNumberEQ applies the EQ predicate on the "source_line_number" field.
func SourceLineNumberEQ(v int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldSourceLineNumber, v))
placeholder

// SourceLineNumberNEQ applies the NEQ predicate on the "source_line_number" field.
func SourceLineNumberNEQ(v int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldSourceLineNumber, v))
placeholder

// SourceLineNumberIn applies the In predicate on the "source_line_number" field.
func SourceLineNumberIn(vs ...int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldSourceLineNumber, vs...))
placeholder

// SourceLineNumberNotIn applies the NotIn predicate on the "source_line_number" field.
func SourceLineNumberNotIn(vs ...int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldSourceLineNumber, vs...))
placeholder

// SourceLineNumberGT applies the GT predicate on the "source_line_number" field.
func SourceLineNumberGT(v int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldSourceLineNumber, v))
placeholder

// SourceLineNumberGTE applies the GTE predicate on the "source_line_number" field.
func SourceLineNumberGTE(v int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldSourceLineNumber, v))
placeholder

// SourceLineNumberLT applies the LT predicate on the "source_line_number" field.
func SourceLineNumberLT(v int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldSourceLineNumber, v))
placeholder

// SourceLineNumberLTE applies the LTE predicate on the "source_line_number" field.
func SourceLineNumberLTE(v int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldSourceLineNumber, v))
placeholder

// SourceLineNumberIsNil applies the IsNil predicate on the "source_line_number" field.
func SourceLineNumberIsNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIsNull(FieldSourceLineNumber))
placeholder

// SourceLineNumberNotNil applies the NotNil predicate on the "source_line_number" field.
func SourceLineNumberNotNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotNull(FieldSourceLineNumber))
placeholder

// SourceByteOffsetEQ applies the EQ predicate on the "source_byte_offset" field.
func SourceByteOffsetEQ(v int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldSourceByteOffset, v))
placeholder

// SourceByteOffsetNEQ applies the NEQ predicate on the "source_byte_offset" field.
func SourceByteOffsetNEQ(v int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldSourceByteOffset, v))
placeholder

// SourceByteOffsetIn applies the In predicate on the "source_byte_offset" field.
func SourceByteOffsetIn(vs ...int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldSourceByteOffset, vs...))
placeholder

// SourceByteOffsetNotIn applies the NotIn predicate on the "source_byte_offset" field.
func SourceByteOffsetNotIn(vs ...int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldSourceByteOffset, vs...))
placeholder

// SourceByteOffsetGT applies the GT predicate on the "source_byte_offset" field.
func SourceByteOffsetGT(v int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldSourceByteOffset, v))
placeholder

// SourceByteOffsetGTE applies the GTE predicate on the "source_byte_offset" field.
func SourceByteOffsetGTE(v int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldSourceByteOffset, v))
placeholder

// SourceByteOffsetLT applies the LT predicate on the "source_byte_offset" field.
func SourceByteOffsetLT(v int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldSourceByteOffset, v))
placeholder

// SourceByteOffsetLTE applies the LTE predicate on the "source_byte_offset" field.
func SourceByteOffsetLTE(v int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldSourceByteOffset, v))
placeholder

// SourceByteOffsetIsNil applies the IsNil predicate on the "source_byte_offset" field.
func SourceByteOffsetIsNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIsNull(FieldSourceByteOffset))
placeholder

// SourceByteOffsetNotNil applies the NotNil predicate on the "source_byte_offset" field.
func SourceByteOffsetNotNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotNull(FieldSourceByteOffset))
placeholder

// SourceByteLengthEQ applies the EQ predicate on the "source_byte_length" field.
func SourceByteLengthEQ(v int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldSourceByteLength, v))
placeholder

// SourceByteLengthNEQ applies the NEQ predicate on the "source_byte_length" field.
func SourceByteLengthNEQ(v int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldSourceByteLength, v))
placeholder

// SourceByteLengthIn applies the In predicate on the "source_byte_length" field.
func SourceByteLengthIn(vs ...int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldSourceByteLength, vs...))
placeholder

// SourceByteLengthNotIn applies the NotIn predicate on the "source_byte_length" field.
func SourceByteLengthNotIn(vs ...int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldSourceByteLength, vs...))
placeholder

// SourceByteLengthGT applies the GT predicate on the "source_byte_length" field.
func SourceByteLengthGT(v int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldSourceByteLength, v))
placeholder

// SourceByteLengthGTE applies the GTE predicate on the "source_byte_length" field.
func SourceByteLengthGTE(v int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldSourceByteLength, v))
placeholder

// SourceByteLengthLT applies the LT predicate on the "source_byte_length" field.
func SourceByteLengthLT(v int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldSourceByteLength, v))
placeholder

// SourceByteLengthLTE applies the LTE predicate on the "source_byte_length" field.
func SourceByteLengthLTE(v int64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldSourceByteLength, v))
placeholder

// SourceByteLengthIsNil applies the IsNil predicate on the "source_byte_length" field.
func SourceByteLengthIsNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIsNull(FieldSourceByteLength))
placeholder

// SourceByteLengthNotNil applies the NotNil predicate on the "source_byte_length" field.
func SourceByteLengthNotNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotNull(FieldSourceByteLength))
placeholder

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldMimeType, v))
placeholder

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldMimeType, v))
placeholder

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldMimeType, vs...))
placeholder

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldMimeType, vs...))
placeholder

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldMimeType, v))
placeholder

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldMimeType, v))
placeholder

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldMimeType, v))
placeholder

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldMimeType, v))
placeholder

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContains(FieldMimeType, v))
placeholder

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasPrefix(FieldMimeType, v))
placeholder

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasSuffix(FieldMimeType, v))
placeholder

// MimeTypeIsNil applies the IsNil predicate on the "mime_type" field.
func MimeTypeIsNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIsNull(FieldMimeType))
placeholder

// MimeTypeNotNil applies the NotNil predicate on the "mime_type" field.
func MimeTypeNotNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotNull(FieldMimeType))
placeholder

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEqualFold(FieldMimeType, v))
placeholder

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContainsFold(FieldMimeType, v))
placeholder

// FileExtensionEQ applies the EQ predicate on the "file_extension" field.
func FileExtensionEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldFileExtension, v))
placeholder

// FileExtensionNEQ applies the NEQ predicate on the "file_extension" field.
func FileExtensionNEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldFileExtension, v))
placeholder

// FileExtensionIn applies the In predicate on the "file_extension" field.
func FileExtensionIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldFileExtension, vs...))
placeholder

// FileExtensionNotIn applies the NotIn predicate on the "file_extension" field.
func FileExtensionNotIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldFileExtension, vs...))
placeholder

// FileExtensionGT applies the GT predicate on the "file_extension" field.
func FileExtensionGT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldFileExtension, v))
placeholder

// FileExtensionGTE applies the GTE predicate on the "file_extension" field.
func FileExtensionGTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldFileExtension, v))
placeholder

// FileExtensionLT applies the LT predicate on the "file_extension" field.
func FileExtensionLT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldFileExtension, v))
placeholder

// FileExtensionLTE applies the LTE predicate on the "file_extension" field.
func FileExtensionLTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldFileExtension, v))
placeholder

// FileExtensionContains applies the Contains predicate on the "file_extension" field.
func FileExtensionContains(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContains(FieldFileExtension, v))
placeholder

// FileExtensionHasPrefix applies the HasPrefix predicate on the "file_extension" field.
func FileExtensionHasPrefix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasPrefix(FieldFileExtension, v))
placeholder

// FileExtensionHasSuffix applies the HasSuffix predicate on the "file_extension" field.
func FileExtensionHasSuffix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasSuffix(FieldFileExtension, v))
placeholder

// FileExtensionIsNil applies the IsNil predicate on the "file_extension" field.
func FileExtensionIsNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIsNull(FieldFileExtension))
placeholder

// FileExtensionNotNil applies the NotNil predicate on the "file_extension" field.
func FileExtensionNotNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotNull(FieldFileExtension))
placeholder

// FileExtensionEqualFold applies the EqualFold predicate on the "file_extension" field.
func FileExtensionEqualFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEqualFold(FieldFileExtension, v))
placeholder

// FileExtensionContainsFold applies the ContainsFold predicate on the "file_extension" field.
func FileExtensionContainsFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContainsFold(FieldFileExtension, v))
placeholder

// ImageCountEQ applies the EQ predicate on the "image_count" field.
func ImageCountEQ(v int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldImageCount, v))
placeholder

// ImageCountNEQ applies the NEQ predicate on the "image_count" field.
func ImageCountNEQ(v int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldImageCount, v))
placeholder

// ImageCountIn applies the In predicate on the "image_count" field.
func ImageCountIn(vs ...int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldImageCount, vs...))
placeholder

// ImageCountNotIn applies the NotIn predicate on the "image_count" field.
func ImageCountNotIn(vs ...int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldImageCount, vs...))
placeholder

// ImageCountGT applies the GT predicate on the "image_count" field.
func ImageCountGT(v int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldImageCount, v))
placeholder

// ImageCountGTE applies the GTE predicate on the "image_count" field.
func ImageCountGTE(v int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldImageCount, v))
placeholder

// ImageCountLT applies the LT predicate on the "image_count" field.
func ImageCountLT(v int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldImageCount, v))
placeholder

// ImageCountLTE applies the LTE predicate on the "image_count" field.
func ImageCountLTE(v int) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldImageCount, v))
placeholder

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldErrorCode, v))
placeholder

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldErrorCode, v))
placeholder

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldErrorCode, vs...))
placeholder

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldErrorCode, vs...))
placeholder

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldErrorCode, v))
placeholder

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldErrorCode, v))
placeholder

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldErrorCode, v))
placeholder

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldErrorCode, v))
placeholder

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContains(FieldErrorCode, v))
placeholder

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasPrefix(FieldErrorCode, v))
placeholder

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasSuffix(FieldErrorCode, v))
placeholder

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIsNull(FieldErrorCode))
placeholder

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotNull(FieldErrorCode))
placeholder

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEqualFold(FieldErrorCode, v))
placeholder

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContainsFold(FieldErrorCode, v))
placeholder

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldErrorMessage, v))
placeholder

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldErrorMessage, v))
placeholder

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldErrorMessage, vs...))
placeholder

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldErrorMessage, vs...))
placeholder

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldErrorMessage, v))
placeholder

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldErrorMessage, v))
placeholder

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldErrorMessage, v))
placeholder

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldErrorMessage, v))
placeholder

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContains(FieldErrorMessage, v))
placeholder

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasPrefix(FieldErrorMessage, v))
placeholder

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldHasSuffix(FieldErrorMessage, v))
placeholder

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIsNull(FieldErrorMessage))
placeholder

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotNull(FieldErrorMessage))
placeholder

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEqualFold(FieldErrorMessage, v))
placeholder

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldContainsFold(FieldErrorMessage, v))
placeholder

// BilledAmountEQ applies the EQ predicate on the "billed_amount" field.
func BilledAmountEQ(v float64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldBilledAmount, v))
placeholder

// BilledAmountNEQ applies the NEQ predicate on the "billed_amount" field.
func BilledAmountNEQ(v float64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldBilledAmount, v))
placeholder

// BilledAmountIn applies the In predicate on the "billed_amount" field.
func BilledAmountIn(vs ...float64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldBilledAmount, vs...))
placeholder

// BilledAmountNotIn applies the NotIn predicate on the "billed_amount" field.
func BilledAmountNotIn(vs ...float64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldBilledAmount, vs...))
placeholder

// BilledAmountGT applies the GT predicate on the "billed_amount" field.
func BilledAmountGT(v float64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldBilledAmount, v))
placeholder

// BilledAmountGTE applies the GTE predicate on the "billed_amount" field.
func BilledAmountGTE(v float64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldBilledAmount, v))
placeholder

// BilledAmountLT applies the LT predicate on the "billed_amount" field.
func BilledAmountLT(v float64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldBilledAmount, v))
placeholder

// BilledAmountLTE applies the LTE predicate on the "billed_amount" field.
func BilledAmountLTE(v float64) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldBilledAmount, v))
placeholder

// BilledAmountIsNil applies the IsNil predicate on the "billed_amount" field.
func BilledAmountIsNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIsNull(FieldBilledAmount))
placeholder

// BilledAmountNotNil applies the NotNil predicate on the "billed_amount" field.
func BilledAmountNotNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotNull(FieldBilledAmount))
placeholder

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldCreatedAt, v))
placeholder

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldCreatedAt, v))
placeholder

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldCreatedAt, vs...))
placeholder

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldCreatedAt, vs...))
placeholder

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldCreatedAt, v))
placeholder

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldCreatedAt, v))
placeholder

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldCreatedAt, v))
placeholder

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldCreatedAt, v))
placeholder

// IndexedAtEQ applies the EQ predicate on the "indexed_at" field.
func IndexedAtEQ(v time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldEQ(FieldIndexedAt, v))
placeholder

// IndexedAtNEQ applies the NEQ predicate on the "indexed_at" field.
func IndexedAtNEQ(v time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNEQ(FieldIndexedAt, v))
placeholder

// IndexedAtIn applies the In predicate on the "indexed_at" field.
func IndexedAtIn(vs ...time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIn(FieldIndexedAt, vs...))
placeholder

// IndexedAtNotIn applies the NotIn predicate on the "indexed_at" field.
func IndexedAtNotIn(vs ...time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotIn(FieldIndexedAt, vs...))
placeholder

// IndexedAtGT applies the GT predicate on the "indexed_at" field.
func IndexedAtGT(v time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGT(FieldIndexedAt, v))
placeholder

// IndexedAtGTE applies the GTE predicate on the "indexed_at" field.
func IndexedAtGTE(v time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldGTE(FieldIndexedAt, v))
placeholder

// IndexedAtLT applies the LT predicate on the "indexed_at" field.
func IndexedAtLT(v time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLT(FieldIndexedAt, v))
placeholder

// IndexedAtLTE applies the LTE predicate on the "indexed_at" field.
func IndexedAtLTE(v time.Time) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldLTE(FieldIndexedAt, v))
placeholder

// IndexedAtIsNil applies the IsNil predicate on the "indexed_at" field.
func IndexedAtIsNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldIsNull(FieldIndexedAt))
placeholder

// IndexedAtNotNil applies the NotNil predicate on the "indexed_at" field.
func IndexedAtNotNil() predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.FieldNotNull(FieldIndexedAt))
placeholder

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BatchImageItem) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.AndPredicates(predicates...))
placeholder

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BatchImageItem) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.OrPredicates(predicates...))
placeholder

// Not applies the not operator on the given predicate.
func Not(p predicate.BatchImageItem) predicate.BatchImageItem {
	return predicate.BatchImageItem(sql.NotPredicates(p))
placeholder
