// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/idempotencyrecord"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// IdempotencyRecordQuery is the builder for querying IdempotencyRecord entities.
type IdempotencyRecordQuery struct {
	config
	ctx        *QueryContext
	order      []idempotencyrecord.OrderOption
	inters     []Interceptor
	predicates []predicate.IdempotencyRecord
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
placeholder

// Where adds a new predicate for the IdempotencyRecordQuery builder.
func (_q *IdempotencyRecordQuery) Where(ps ...predicate.IdempotencyRecord) *IdempotencyRecordQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
placeholder

// Limit the number of records to be returned by this query.
func (_q *IdempotencyRecordQuery) Limit(limit int) *IdempotencyRecordQuery {
	_q.ctx.Limit = &limit
	return _q
placeholder

// Offset to start from.
func (_q *IdempotencyRecordQuery) Offset(offset int) *IdempotencyRecordQuery {
	_q.ctx.Offset = &offset
	return _q
placeholder

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *IdempotencyRecordQuery) Unique(unique bool) *IdempotencyRecordQuery {
	_q.ctx.Unique = &unique
	return _q
placeholder

// Order specifies how the records should be ordered.
func (_q *IdempotencyRecordQuery) Order(o ...idempotencyrecord.OrderOption) *IdempotencyRecordQuery {
	_q.order = append(_q.order, o...)
	return _q
placeholder

// First returns the first IdempotencyRecord entity from the query.
// Returns a *NotFoundError when no IdempotencyRecord was found.
func (_q *IdempotencyRecordQuery) First(ctx context.Context) (*IdempotencyRecord, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
placeholder
	if len(nodes) == 0 {
		return nil, &NotFoundError{idempotencyrecord.Labelplaceholder
placeholder
	return nodes[0], nil
placeholder

// FirstX is like First, but panics if an error occurs.
func (_q *IdempotencyRecordQuery) FirstX(ctx context.Context) *IdempotencyRecord {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
placeholder
	return node
placeholder

// FirstID returns the first IdempotencyRecord ID from the query.
// Returns a *NotFoundError when no IdempotencyRecord ID was found.
func (_q *IdempotencyRecordQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
placeholder
	if len(ids) == 0 {
		err = &NotFoundError{idempotencyrecord.Labelplaceholder
		return
placeholder
	return ids[0], nil
placeholder

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *IdempotencyRecordQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
placeholder
	return id
placeholder

// Only returns a single IdempotencyRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IdempotencyRecord entity is found.
// Returns a *NotFoundError when no IdempotencyRecord entities are found.
func (_q *IdempotencyRecordQuery) Only(ctx context.Context) (*IdempotencyRecord, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
placeholder
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{idempotencyrecord.Labelplaceholder
	default:
		return nil, &NotSingularError{idempotencyrecord.Labelplaceholder
placeholder
placeholder

// OnlyX is like Only, but panics if an error occurs.
func (_q *IdempotencyRecordQuery) OnlyX(ctx context.Context) *IdempotencyRecord {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
placeholder
	return node
placeholder

// OnlyID is like Only, but returns the only IdempotencyRecord ID in the query.
// Returns a *NotSingularError when more than one IdempotencyRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *IdempotencyRecordQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
placeholder
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{idempotencyrecord.Labelplaceholder
	default:
		err = &NotSingularError{idempotencyrecord.Labelplaceholder
placeholder
	return
placeholder

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *IdempotencyRecordQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
placeholder
	return id
placeholder

// All executes the query and returns a list of IdempotencyRecords.
func (_q *IdempotencyRecordQuery) All(ctx context.Context) ([]*IdempotencyRecord, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
placeholder
	qr := querierAll[[]*IdempotencyRecord, *IdempotencyRecordQuery]()
	return withInterceptors[[]*IdempotencyRecord](ctx, _q, qr, _q.inters)
placeholder

// AllX is like All, but panics if an error occurs.
func (_q *IdempotencyRecordQuery) AllX(ctx context.Context) []*IdempotencyRecord {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
placeholder
	return nodes
placeholder

// IDs executes the query and returns a list of IdempotencyRecord IDs.
func (_q *IdempotencyRecordQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
placeholder
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(idempotencyrecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
placeholder
	return ids, nil
placeholder

// IDsX is like IDs, but panics if an error occurs.
func (_q *IdempotencyRecordQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
placeholder
	return ids
placeholder

// Count returns the count of the given query.
func (_q *IdempotencyRecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
placeholder
	return withInterceptors[int](ctx, _q, querierCount[*IdempotencyRecordQuery](), _q.inters)
placeholder

// CountX is like Count, but panics if an error occurs.
func (_q *IdempotencyRecordQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
placeholder
	return count
placeholder

// Exist returns true if the query has elements in the graph.
func (_q *IdempotencyRecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
placeholder
placeholder

// ExistX is like Exist, but panics if an error occurs.
func (_q *IdempotencyRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
placeholder
	return exist
placeholder

// Clone returns a duplicate of the IdempotencyRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *IdempotencyRecordQuery) Clone() *IdempotencyRecordQuery {
	if _q == nil {
		return nil
placeholder
	return &IdempotencyRecordQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]idempotencyrecord.OrderOption{placeholder, _q.order...),
		inters:     append([]Interceptor{placeholder, _q.inters...),
		predicates: append([]predicate.IdempotencyRecord{placeholder, _q.predicates...),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
placeholder
placeholder

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//placeholder
//
//	client.IdempotencyRecord.Query().
//		GroupBy(idempotencyrecord.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *IdempotencyRecordQuery) GroupBy(field string, fields ...string) *IdempotencyRecordGroupBy {
	_q.ctx.Fields = append([]string{fieldplaceholder, fields...)
	grbuild := &IdempotencyRecordGroupBy{build: _qplaceholder
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = idempotencyrecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
placeholder

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//placeholder
//
//	client.IdempotencyRecord.Query().
//		Select(idempotencyrecord.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *IdempotencyRecordQuery) Select(fields ...string) *IdempotencyRecordSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &IdempotencyRecordSelect{IdempotencyRecordQuery: _qplaceholder
	sbuild.label = idempotencyrecord.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
placeholder

// Aggregate returns a IdempotencyRecordSelect configured with the given aggregations.
func (_q *IdempotencyRecordQuery) Aggregate(fns ...AggregateFunc) *IdempotencyRecordSelect {
	return _q.Select().Aggregate(fns...)
placeholder

func (_q *IdempotencyRecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
	placeholder
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
		placeholder
	placeholder
placeholder
	for _, f := range _q.ctx.Fields {
		if !idempotencyrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)placeholder
	placeholder
placeholder
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
	placeholder
		_q.sql = prev
placeholder
	return nil
placeholder

func (_q *IdempotencyRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IdempotencyRecord, error) {
	var (
		nodes = []*IdempotencyRecord{placeholder
		_spec = _q.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IdempotencyRecord).scanValues(nil, columns)
placeholder
	_spec.Assign = func(columns []string, values []any) error {
		node := &IdempotencyRecord{config: _q.configplaceholder
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
placeholder
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
placeholder
	for i := range hooks {
		hooks[i](ctx, _spec)
placeholder
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
placeholder
	if len(nodes) == 0 {
		return nodes, nil
placeholder
	return nodes, nil
placeholder

func (_q *IdempotencyRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
placeholder
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
placeholder
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
placeholder

func (_q *IdempotencyRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(idempotencyrecord.Table, idempotencyrecord.Columns, sqlgraph.NewFieldSpec(idempotencyrecord.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
placeholder else if _q.path != nil {
		_spec.Unique = true
placeholder
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, idempotencyrecord.FieldID)
		for i := range fields {
			if fields[i] != idempotencyrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		placeholder
	placeholder
placeholder
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
		placeholder
	placeholder
placeholder
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
placeholder
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
placeholder
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
		placeholder
	placeholder
placeholder
	return _spec
placeholder

func (_q *IdempotencyRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(idempotencyrecord.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = idempotencyrecord.Columns
placeholder
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
placeholder
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
placeholder
	for _, m := range _q.modifiers {
		m(selector)
placeholder
	for _, p := range _q.predicates {
		p(selector)
placeholder
	for _, p := range _q.order {
		p(selector)
placeholder
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
placeholder
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
placeholder
	return selector
placeholder

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *IdempotencyRecordQuery) ForUpdate(opts ...sql.LockOption) *IdempotencyRecordQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
placeholder
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
placeholder)
	return _q
placeholder

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *IdempotencyRecordQuery) ForShare(opts ...sql.LockOption) *IdempotencyRecordQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
placeholder
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
placeholder)
	return _q
placeholder

// IdempotencyRecordGroupBy is the group-by builder for IdempotencyRecord entities.
type IdempotencyRecordGroupBy struct {
	selector
	build *IdempotencyRecordQuery
placeholder

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *IdempotencyRecordGroupBy) Aggregate(fns ...AggregateFunc) *IdempotencyRecordGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
placeholder

// Scan applies the selector query and scans the result into the given value.
func (_g *IdempotencyRecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
placeholder
	return scanWithInterceptors[*IdempotencyRecordQuery, *IdempotencyRecordGroupBy](ctx, _g.build, _g, _g.build.inters, v)
placeholder

func (_g *IdempotencyRecordGroupBy) sqlScan(ctx context.Context, root *IdempotencyRecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
placeholder
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
	placeholder
		columns = append(columns, aggregation...)
		selector.Select(columns...)
placeholder
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
placeholder
	rows := &sql.Rows{placeholder
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
placeholder
	defer rows.Close()
	return sql.ScanSlice(rows, v)
placeholder

// IdempotencyRecordSelect is the builder for selecting fields of IdempotencyRecord entities.
type IdempotencyRecordSelect struct {
	*IdempotencyRecordQuery
	selector
placeholder

// Aggregate adds the given aggregation functions to the selector query.
func (_s *IdempotencyRecordSelect) Aggregate(fns ...AggregateFunc) *IdempotencyRecordSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
placeholder

// Scan applies the selector query and scans the result into the given value.
func (_s *IdempotencyRecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
placeholder
	return scanWithInterceptors[*IdempotencyRecordQuery, *IdempotencyRecordSelect](ctx, _s.IdempotencyRecordQuery, _s, _s.inters, v)
placeholder

func (_s *IdempotencyRecordSelect) sqlScan(ctx context.Context, root *IdempotencyRecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
placeholder
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
placeholder
	rows := &sql.Rows{placeholder
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
placeholder
	defer rows.Close()
	return sql.ScanSlice(rows, v)
placeholder
