// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"encoding/json/jsontext"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/usagecleanuptask"
)

// UsageCleanupTask is the model entity for the UsageCleanupTask schema.
type UsageCleanupTask struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Filters holds the value of the "filters" field.
	Filters jsontext.Value `json:"filters,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// DeletedRows holds the value of the "deleted_rows" field.
	DeletedRows int64 `json:"deleted_rows,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// CanceledBy holds the value of the "canceled_by" field.
	CanceledBy *int64 `json:"canceled_by,omitempty"`
	// CanceledAt holds the value of the "canceled_at" field.
	CanceledAt *time.Time `json:"canceled_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt   *time.Time `json:"finished_at,omitempty"`
	selectValues sql.SelectValues
placeholder

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageCleanupTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagecleanuptask.FieldFilters:
			values[i] = new([]byte)
		case usagecleanuptask.FieldID, usagecleanuptask.FieldCreatedBy, usagecleanuptask.FieldDeletedRows, usagecleanuptask.FieldCanceledBy:
			values[i] = new(sql.NullInt64)
		case usagecleanuptask.FieldStatus, usagecleanuptask.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case usagecleanuptask.FieldCreatedAt, usagecleanuptask.FieldUpdatedAt, usagecleanuptask.FieldCanceledAt, usagecleanuptask.FieldStartedAt, usagecleanuptask.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
	placeholder
placeholder
	return values, nil
placeholder

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageCleanupTask fields.
func (_m *UsageCleanupTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
placeholder
	for i := range columns {
		switch columns[i] {
		case usagecleanuptask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
		placeholder
			_m.ID = int64(value.Int64)
		case usagecleanuptask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
		placeholder else if value.Valid {
				_m.CreatedAt = value.Time
		placeholder
		case usagecleanuptask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
		placeholder else if value.Valid {
				_m.UpdatedAt = value.Time
		placeholder
		case usagecleanuptask.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
		placeholder else if value.Valid {
				_m.Status = value.String
		placeholder
		case usagecleanuptask.FieldFilters:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field filters", values[i])
		placeholder else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Filters); err != nil {
					return fmt.Errorf("unmarshal field filters: %w", err)
			placeholder
		placeholder
		case usagecleanuptask.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
		placeholder else if value.Valid {
				_m.CreatedBy = value.Int64
		placeholder
		case usagecleanuptask.FieldDeletedRows:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_rows", values[i])
		placeholder else if value.Valid {
				_m.DeletedRows = value.Int64
		placeholder
		case usagecleanuptask.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
		placeholder else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
		placeholder
		case usagecleanuptask.FieldCanceledBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field canceled_by", values[i])
		placeholder else if value.Valid {
				_m.CanceledBy = new(int64)
				*_m.CanceledBy = value.Int64
		placeholder
		case usagecleanuptask.FieldCanceledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field canceled_at", values[i])
		placeholder else if value.Valid {
				_m.CanceledAt = new(time.Time)
				*_m.CanceledAt = value.Time
		placeholder
		case usagecleanuptask.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
		placeholder else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
		placeholder
		case usagecleanuptask.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
		placeholder else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
		placeholder
		default:
			_m.selectValues.Set(columns[i], values[i])
	placeholder
placeholder
	return nil
placeholder

// Value returns the ent.Value that was dynamically selected and assigned to the UsageCleanupTask.
// This includes values selected through modifiers, order, etc.
func (_m *UsageCleanupTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
placeholder

// Update returns a builder for updating this UsageCleanupTask.
// Note that you need to call UsageCleanupTask.Unwrap() before calling this method if this UsageCleanupTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageCleanupTask) Update() *UsageCleanupTaskUpdateOne {
	return NewUsageCleanupTaskClient(_m.config).UpdateOne(_m)
placeholder

// Unwrap unwraps the UsageCleanupTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageCleanupTask) Unwrap() *UsageCleanupTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageCleanupTask is not a transactional entity")
placeholder
	_m.config.driver = _tx.drv
	return _m
placeholder

// String implements the fmt.Stringer.
func (_m *UsageCleanupTask) String() string {
	var builder strings.Builder
	builder.WriteString("UsageCleanupTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("filters=")
	builder.WriteString(fmt.Sprintf("%v", _m.Filters))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("deleted_rows=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedRows))
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
placeholder
	builder.WriteString(", ")
	if v := _m.CanceledBy; v != nil {
		builder.WriteString("canceled_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
placeholder
	builder.WriteString(", ")
	if v := _m.CanceledAt; v != nil {
		builder.WriteString("canceled_at=")
		builder.WriteString(v.Format(time.ANSIC))
placeholder
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
placeholder
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
placeholder
	builder.WriteByte(')')
	return builder.String()
placeholder

// UsageCleanupTasks is a parsable slice of UsageCleanupTask.
type UsageCleanupTasks []*UsageCleanupTask
