// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userplatformquota"
)

// UserPlatformQuota is the model entity for the UserPlatformQuota schema.
type UserPlatformQuota struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// DailyLimitUsd holds the value of the "daily_limit_usd" field.
	DailyLimitUsd *float64 `json:"daily_limit_usd,omitempty"`
	// WeeklyLimitUsd holds the value of the "weekly_limit_usd" field.
	WeeklyLimitUsd *float64 `json:"weekly_limit_usd,omitempty"`
	// MonthlyLimitUsd holds the value of the "monthly_limit_usd" field.
	MonthlyLimitUsd *float64 `json:"monthly_limit_usd,omitempty"`
	// DailyUsageUsd holds the value of the "daily_usage_usd" field.
	DailyUsageUsd float64 `json:"daily_usage_usd,omitempty"`
	// WeeklyUsageUsd holds the value of the "weekly_usage_usd" field.
	WeeklyUsageUsd float64 `json:"weekly_usage_usd,omitempty"`
	// MonthlyUsageUsd holds the value of the "monthly_usage_usd" field.
	MonthlyUsageUsd float64 `json:"monthly_usage_usd,omitempty"`
	// DailyWindowStart holds the value of the "daily_window_start" field.
	DailyWindowStart *time.Time `json:"daily_window_start,omitempty"`
	// WeeklyWindowStart holds the value of the "weekly_window_start" field.
	WeeklyWindowStart *time.Time `json:"weekly_window_start,omitempty"`
	// MonthlyWindowStart holds the value of the "monthly_window_start" field.
	MonthlyWindowStart *time.Time `json:"monthly_window_start,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserPlatformQuotaQuery when eager-loading is set.
	Edges        UserPlatformQuotaEdges `json:"edges"`
	selectValues sql.SelectValues
placeholder

// UserPlatformQuotaEdges holds the relations/edges for other nodes in the graph.
type UserPlatformQuotaEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
placeholder

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserPlatformQuotaEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
placeholder else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Labelplaceholder
placeholder
	return nil, &NotLoadedError{edge: "user"placeholder
placeholder

// scanValues returns the types for scanning values from sql.Rows.
func (*UserPlatformQuota) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userplatformquota.FieldDailyLimitUsd, userplatformquota.FieldWeeklyLimitUsd, userplatformquota.FieldMonthlyLimitUsd, userplatformquota.FieldDailyUsageUsd, userplatformquota.FieldWeeklyUsageUsd, userplatformquota.FieldMonthlyUsageUsd:
			values[i] = new(sql.NullFloat64)
		case userplatformquota.FieldID, userplatformquota.FieldUserID:
			values[i] = new(sql.NullInt64)
		case userplatformquota.FieldPlatform:
			values[i] = new(sql.NullString)
		case userplatformquota.FieldCreatedAt, userplatformquota.FieldUpdatedAt, userplatformquota.FieldDeletedAt, userplatformquota.FieldDailyWindowStart, userplatformquota.FieldWeeklyWindowStart, userplatformquota.FieldMonthlyWindowStart:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
	placeholder
placeholder
	return values, nil
placeholder

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserPlatformQuota fields.
func (_m *UserPlatformQuota) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
placeholder
	for i := range columns {
		switch columns[i] {
		case userplatformquota.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
		placeholder
			_m.ID = int64(value.Int64)
		case userplatformquota.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
		placeholder else if value.Valid {
				_m.CreatedAt = value.Time
		placeholder
		case userplatformquota.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
		placeholder else if value.Valid {
				_m.UpdatedAt = value.Time
		placeholder
		case userplatformquota.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
		placeholder else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
		placeholder
		case userplatformquota.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
		placeholder else if value.Valid {
				_m.UserID = value.Int64
		placeholder
		case userplatformquota.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
		placeholder else if value.Valid {
				_m.Platform = value.String
		placeholder
		case userplatformquota.FieldDailyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_limit_usd", values[i])
		placeholder else if value.Valid {
				_m.DailyLimitUsd = new(float64)
				*_m.DailyLimitUsd = value.Float64
		placeholder
		case userplatformquota.FieldWeeklyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_limit_usd", values[i])
		placeholder else if value.Valid {
				_m.WeeklyLimitUsd = new(float64)
				*_m.WeeklyLimitUsd = value.Float64
		placeholder
		case userplatformquota.FieldMonthlyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_limit_usd", values[i])
		placeholder else if value.Valid {
				_m.MonthlyLimitUsd = new(float64)
				*_m.MonthlyLimitUsd = value.Float64
		placeholder
		case userplatformquota.FieldDailyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_usage_usd", values[i])
		placeholder else if value.Valid {
				_m.DailyUsageUsd = value.Float64
		placeholder
		case userplatformquota.FieldWeeklyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_usage_usd", values[i])
		placeholder else if value.Valid {
				_m.WeeklyUsageUsd = value.Float64
		placeholder
		case userplatformquota.FieldMonthlyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_usage_usd", values[i])
		placeholder else if value.Valid {
				_m.MonthlyUsageUsd = value.Float64
		placeholder
		case userplatformquota.FieldDailyWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field daily_window_start", values[i])
		placeholder else if value.Valid {
				_m.DailyWindowStart = new(time.Time)
				*_m.DailyWindowStart = value.Time
		placeholder
		case userplatformquota.FieldWeeklyWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_window_start", values[i])
		placeholder else if value.Valid {
				_m.WeeklyWindowStart = new(time.Time)
				*_m.WeeklyWindowStart = value.Time
		placeholder
		case userplatformquota.FieldMonthlyWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_window_start", values[i])
		placeholder else if value.Valid {
				_m.MonthlyWindowStart = new(time.Time)
				*_m.MonthlyWindowStart = value.Time
		placeholder
		default:
			_m.selectValues.Set(columns[i], values[i])
	placeholder
placeholder
	return nil
placeholder

// Value returns the ent.Value that was dynamically selected and assigned to the UserPlatformQuota.
// This includes values selected through modifiers, order, etc.
func (_m *UserPlatformQuota) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
placeholder

// QueryUser queries the "user" edge of the UserPlatformQuota entity.
func (_m *UserPlatformQuota) QueryUser() *UserQuery {
	return NewUserPlatformQuotaClient(_m.config).QueryUser(_m)
placeholder

// Update returns a builder for updating this UserPlatformQuota.
// Note that you need to call UserPlatformQuota.Unwrap() before calling this method if this UserPlatformQuota
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserPlatformQuota) Update() *UserPlatformQuotaUpdateOne {
	return NewUserPlatformQuotaClient(_m.config).UpdateOne(_m)
placeholder

// Unwrap unwraps the UserPlatformQuota entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserPlatformQuota) Unwrap() *UserPlatformQuota {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserPlatformQuota is not a transactional entity")
placeholder
	_m.config.driver = _tx.drv
	return _m
placeholder

// String implements the fmt.Stringer.
func (_m *UserPlatformQuota) String() string {
	var builder strings.Builder
	builder.WriteString("UserPlatformQuota(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
placeholder
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	if v := _m.DailyLimitUsd; v != nil {
		builder.WriteString("daily_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
placeholder
	builder.WriteString(", ")
	if v := _m.WeeklyLimitUsd; v != nil {
		builder.WriteString("weekly_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
placeholder
	builder.WriteString(", ")
	if v := _m.MonthlyLimitUsd; v != nil {
		builder.WriteString("monthly_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
placeholder
	builder.WriteString(", ")
	builder.WriteString("daily_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyUsageUsd))
	builder.WriteString(", ")
	builder.WriteString("weekly_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.WeeklyUsageUsd))
	builder.WriteString(", ")
	builder.WriteString("monthly_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthlyUsageUsd))
	builder.WriteString(", ")
	if v := _m.DailyWindowStart; v != nil {
		builder.WriteString("daily_window_start=")
		builder.WriteString(v.Format(time.ANSIC))
placeholder
	builder.WriteString(", ")
	if v := _m.WeeklyWindowStart; v != nil {
		builder.WriteString("weekly_window_start=")
		builder.WriteString(v.Format(time.ANSIC))
placeholder
	builder.WriteString(", ")
	if v := _m.MonthlyWindowStart; v != nil {
		builder.WriteString("monthly_window_start=")
		builder.WriteString(v.Format(time.ANSIC))
placeholder
	builder.WriteByte(')')
	return builder.String()
placeholder

// UserPlatformQuotaSlice is a parsable slice of UserPlatformQuota.
type UserPlatformQuotaSlice []*UserPlatformQuota
