// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userallowedgroup"
)

// UserAllowedGroupUpdate is the builder for updating UserAllowedGroup entities.
type UserAllowedGroupUpdate struct {
	config
	hooks    []Hook
	mutation *UserAllowedGroupMutation
placeholder

// Where appends a list predicates to the UserAllowedGroupUpdate builder.
func (_u *UserAllowedGroupUpdate) Where(ps ...predicate.UserAllowedGroup) *UserAllowedGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
placeholder

// SetUserID sets the "user_id" field.
func (_u *UserAllowedGroupUpdate) SetUserID(v int64) *UserAllowedGroupUpdate {
	_u.mutation.SetUserID(v)
	return _u
placeholder

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAllowedGroupUpdate) SetNillableUserID(v *int64) *UserAllowedGroupUpdate {
	if v != nil {
		_u.SetUserID(*v)
placeholder
	return _u
placeholder

// SetGroupID sets the "group_id" field.
func (_u *UserAllowedGroupUpdate) SetGroupID(v int64) *UserAllowedGroupUpdate {
	_u.mutation.SetGroupID(v)
	return _u
placeholder

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserAllowedGroupUpdate) SetNillableGroupID(v *int64) *UserAllowedGroupUpdate {
	if v != nil {
		_u.SetGroupID(*v)
placeholder
	return _u
placeholder

// SetUser sets the "user" edge to the User entity.
func (_u *UserAllowedGroupUpdate) SetUser(v *User) *UserAllowedGroupUpdate {
	return _u.SetUserID(v.ID)
placeholder

// SetGroup sets the "group" edge to the Group entity.
func (_u *UserAllowedGroupUpdate) SetGroup(v *Group) *UserAllowedGroupUpdate {
	return _u.SetGroupID(v.ID)
placeholder

// Mutation returns the UserAllowedGroupMutation object of the builder.
func (_u *UserAllowedGroupUpdate) Mutation() *UserAllowedGroupMutation {
	return _u.mutation
placeholder

// ClearUser clears the "user" edge to the User entity.
func (_u *UserAllowedGroupUpdate) ClearUser() *UserAllowedGroupUpdate {
	_u.mutation.ClearUser()
	return _u
placeholder

// ClearGroup clears the "group" edge to the Group entity.
func (_u *UserAllowedGroupUpdate) ClearGroup() *UserAllowedGroupUpdate {
	_u.mutation.ClearGroup()
	return _u
placeholder

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAllowedGroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
placeholder

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAllowedGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
placeholder
	return affected
placeholder

// Exec executes the query.
func (_u *UserAllowedGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
placeholder

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAllowedGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
placeholder
placeholder

// check runs all checks and user-defined validators on the builder.
func (_u *UserAllowedGroupUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAllowedGroup.user"`)
placeholder
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAllowedGroup.group"`)
placeholder
	return nil
placeholder

func (_u *UserAllowedGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
placeholder
	_spec := sqlgraph.NewUpdateSpec(userallowedgroup.Table, userallowedgroup.Columns, sqlgraph.NewFieldSpec(userallowedgroup.FieldUserID, field.TypeInt64), sqlgraph.NewFieldSpec(userallowedgroup.FieldGroupID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
		placeholder
	placeholder
placeholder
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userallowedgroup.UserTable,
			Columns: []string{userallowedgroup.UserColumnplaceholder,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
		placeholder,
	placeholder
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
placeholder
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userallowedgroup.UserTable,
			Columns: []string{userallowedgroup.UserColumnplaceholder,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
		placeholder,
	placeholder
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	placeholder
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
placeholder
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userallowedgroup.GroupTable,
			Columns: []string{userallowedgroup.GroupColumnplaceholder,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
		placeholder,
	placeholder
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
placeholder
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userallowedgroup.GroupTable,
			Columns: []string{userallowedgroup.GroupColumnplaceholder,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
		placeholder,
	placeholder
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	placeholder
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
placeholder
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userallowedgroup.Labelplaceholder
	placeholder else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: errplaceholder
	placeholder
		return 0, err
placeholder
	_u.mutation.done = true
	return _node, nil
placeholder

// UserAllowedGroupUpdateOne is the builder for updating a single UserAllowedGroup entity.
type UserAllowedGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAllowedGroupMutation
placeholder

// SetUserID sets the "user_id" field.
func (_u *UserAllowedGroupUpdateOne) SetUserID(v int64) *UserAllowedGroupUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
placeholder

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAllowedGroupUpdateOne) SetNillableUserID(v *int64) *UserAllowedGroupUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
placeholder
	return _u
placeholder

// SetGroupID sets the "group_id" field.
func (_u *UserAllowedGroupUpdateOne) SetGroupID(v int64) *UserAllowedGroupUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
placeholder

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserAllowedGroupUpdateOne) SetNillableGroupID(v *int64) *UserAllowedGroupUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
placeholder
	return _u
placeholder

// SetUser sets the "user" edge to the User entity.
func (_u *UserAllowedGroupUpdateOne) SetUser(v *User) *UserAllowedGroupUpdateOne {
	return _u.SetUserID(v.ID)
placeholder

// SetGroup sets the "group" edge to the Group entity.
func (_u *UserAllowedGroupUpdateOne) SetGroup(v *Group) *UserAllowedGroupUpdateOne {
	return _u.SetGroupID(v.ID)
placeholder

// Mutation returns the UserAllowedGroupMutation object of the builder.
func (_u *UserAllowedGroupUpdateOne) Mutation() *UserAllowedGroupMutation {
	return _u.mutation
placeholder

// ClearUser clears the "user" edge to the User entity.
func (_u *UserAllowedGroupUpdateOne) ClearUser() *UserAllowedGroupUpdateOne {
	_u.mutation.ClearUser()
	return _u
placeholder

// ClearGroup clears the "group" edge to the Group entity.
func (_u *UserAllowedGroupUpdateOne) ClearGroup() *UserAllowedGroupUpdateOne {
	_u.mutation.ClearGroup()
	return _u
placeholder

// Where appends a list predicates to the UserAllowedGroupUpdate builder.
func (_u *UserAllowedGroupUpdateOne) Where(ps ...predicate.UserAllowedGroup) *UserAllowedGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
placeholder

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAllowedGroupUpdateOne) Select(field string, fields ...string) *UserAllowedGroupUpdateOne {
	_u.fields = append([]string{fieldplaceholder, fields...)
	return _u
placeholder

// Save executes the query and returns the updated UserAllowedGroup entity.
func (_u *UserAllowedGroupUpdateOne) Save(ctx context.Context) (*UserAllowedGroup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
placeholder

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAllowedGroupUpdateOne) SaveX(ctx context.Context) *UserAllowedGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
placeholder
	return node
placeholder

// Exec executes the query on the entity.
func (_u *UserAllowedGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
placeholder

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAllowedGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
placeholder
placeholder

// check runs all checks and user-defined validators on the builder.
func (_u *UserAllowedGroupUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAllowedGroup.user"`)
placeholder
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAllowedGroup.group"`)
placeholder
	return nil
placeholder

func (_u *UserAllowedGroupUpdateOne) sqlSave(ctx context.Context) (_node *UserAllowedGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
placeholder
	_spec := sqlgraph.NewUpdateSpec(userallowedgroup.Table, userallowedgroup.Columns, sqlgraph.NewFieldSpec(userallowedgroup.FieldUserID, field.TypeInt64), sqlgraph.NewFieldSpec(userallowedgroup.FieldGroupID, field.TypeInt64))
	if id, ok := _u.mutation.UserID(); !ok {
		return nil, &ValidationError{Name: "user_id", err: errors.New(`ent: missing "UserAllowedGroup.user_id" for update`)placeholder
placeholder else {
		_spec.Node.CompositeID[0].Value = id
placeholder
	if id, ok := _u.mutation.GroupID(); !ok {
		return nil, &ValidationError{Name: "group_id", err: errors.New(`ent: missing "UserAllowedGroup.group_id" for update`)placeholder
placeholder else {
		_spec.Node.CompositeID[1].Value = id
placeholder
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !userallowedgroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)placeholder
		placeholder
			_spec.Node.Columns[i] = f
	placeholder
placeholder
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
		placeholder
	placeholder
placeholder
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userallowedgroup.UserTable,
			Columns: []string{userallowedgroup.UserColumnplaceholder,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
		placeholder,
	placeholder
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
placeholder
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userallowedgroup.UserTable,
			Columns: []string{userallowedgroup.UserColumnplaceholder,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
		placeholder,
	placeholder
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	placeholder
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
placeholder
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userallowedgroup.GroupTable,
			Columns: []string{userallowedgroup.GroupColumnplaceholder,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
		placeholder,
	placeholder
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
placeholder
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userallowedgroup.GroupTable,
			Columns: []string{userallowedgroup.GroupColumnplaceholder,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
		placeholder,
	placeholder
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	placeholder
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
placeholder
	_node = &UserAllowedGroup{config: _u.configplaceholder
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userallowedgroup.Labelplaceholder
	placeholder else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: errplaceholder
	placeholder
		return nil, err
placeholder
	_u.mutation.done = true
	return _node, nil
placeholder
