// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/userattributedefinition"
)

// UserAttributeDefinition is the model entity for the UserAttributeDefinition schema.
type UserAttributeDefinition struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Options holds the value of the "options" field.
	Options []map[string]interface{placeholder `json:"options,omitempty"`
	// Required holds the value of the "required" field.
	Required bool `json:"required,omitempty"`
	// Validation holds the value of the "validation" field.
	Validation map[string]interface{placeholder `json:"validation,omitempty"`
	// Placeholder holds the value of the "placeholder" field.
	Placeholder string `json:"placeholder,omitempty"`
	// DisplayOrder holds the value of the "display_order" field.
	DisplayOrder int `json:"display_order,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserAttributeDefinitionQuery when eager-loading is set.
	Edges        UserAttributeDefinitionEdges `json:"edges"`
	selectValues sql.SelectValues
placeholder

// UserAttributeDefinitionEdges holds the relations/edges for other nodes in the graph.
type UserAttributeDefinitionEdges struct {
	// Values holds the value of the values edge.
	Values []*UserAttributeValue `json:"values,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
placeholder

// ValuesOrErr returns the Values value or an error if the edge
// was not loaded in eager-loading.
func (e UserAttributeDefinitionEdges) ValuesOrErr() ([]*UserAttributeValue, error) {
	if e.loadedTypes[0] {
		return e.Values, nil
placeholder
	return nil, &NotLoadedError{edge: "values"placeholder
placeholder

// scanValues returns the types for scanning values from sql.Rows.
func (*UserAttributeDefinition) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userattributedefinition.FieldOptions, userattributedefinition.FieldValidation:
			values[i] = new([]byte)
		case userattributedefinition.FieldRequired, userattributedefinition.FieldEnabled:
			values[i] = new(sql.NullBool)
		case userattributedefinition.FieldID, userattributedefinition.FieldDisplayOrder:
			values[i] = new(sql.NullInt64)
		case userattributedefinition.FieldKey, userattributedefinition.FieldName, userattributedefinition.FieldDescription, userattributedefinition.FieldType, userattributedefinition.FieldPlaceholder:
			values[i] = new(sql.NullString)
		case userattributedefinition.FieldCreatedAt, userattributedefinition.FieldUpdatedAt, userattributedefinition.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
	placeholder
placeholder
	return values, nil
placeholder

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserAttributeDefinition fields.
func (_m *UserAttributeDefinition) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
placeholder
	for i := range columns {
		switch columns[i] {
		case userattributedefinition.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
		placeholder
			_m.ID = int64(value.Int64)
		case userattributedefinition.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
		placeholder else if value.Valid {
				_m.CreatedAt = value.Time
		placeholder
		case userattributedefinition.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
		placeholder else if value.Valid {
				_m.UpdatedAt = value.Time
		placeholder
		case userattributedefinition.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
		placeholder else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
		placeholder
		case userattributedefinition.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
		placeholder else if value.Valid {
				_m.Key = value.String
		placeholder
		case userattributedefinition.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
		placeholder else if value.Valid {
				_m.Name = value.String
		placeholder
		case userattributedefinition.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
		placeholder else if value.Valid {
				_m.Description = value.String
		placeholder
		case userattributedefinition.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
		placeholder else if value.Valid {
				_m.Type = value.String
		placeholder
		case userattributedefinition.FieldOptions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field options", values[i])
		placeholder else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Options); err != nil {
					return fmt.Errorf("unmarshal field options: %w", err)
			placeholder
		placeholder
		case userattributedefinition.FieldRequired:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field required", values[i])
		placeholder else if value.Valid {
				_m.Required = value.Bool
		placeholder
		case userattributedefinition.FieldValidation:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field validation", values[i])
		placeholder else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Validation); err != nil {
					return fmt.Errorf("unmarshal field validation: %w", err)
			placeholder
		placeholder
		case userattributedefinition.FieldPlaceholder:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field placeholder", values[i])
		placeholder else if value.Valid {
				_m.Placeholder = value.String
		placeholder
		case userattributedefinition.FieldDisplayOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field display_order", values[i])
		placeholder else if value.Valid {
				_m.DisplayOrder = int(value.Int64)
		placeholder
		case userattributedefinition.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
		placeholder else if value.Valid {
				_m.Enabled = value.Bool
		placeholder
		default:
			_m.selectValues.Set(columns[i], values[i])
	placeholder
placeholder
	return nil
placeholder

// Value returns the ent.Value that was dynamically selected and assigned to the UserAttributeDefinition.
// This includes values selected through modifiers, order, etc.
func (_m *UserAttributeDefinition) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
placeholder

// QueryValues queries the "values" edge of the UserAttributeDefinition entity.
func (_m *UserAttributeDefinition) QueryValues() *UserAttributeValueQuery {
	return NewUserAttributeDefinitionClient(_m.config).QueryValues(_m)
placeholder

// Update returns a builder for updating this UserAttributeDefinition.
// Note that you need to call UserAttributeDefinition.Unwrap() before calling this method if this UserAttributeDefinition
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserAttributeDefinition) Update() *UserAttributeDefinitionUpdateOne {
	return NewUserAttributeDefinitionClient(_m.config).UpdateOne(_m)
placeholder

// Unwrap unwraps the UserAttributeDefinition entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserAttributeDefinition) Unwrap() *UserAttributeDefinition {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserAttributeDefinition is not a transactional entity")
placeholder
	_m.config.driver = _tx.drv
	return _m
placeholder

// String implements the fmt.Stringer.
func (_m *UserAttributeDefinition) String() string {
	var builder strings.Builder
	builder.WriteString("UserAttributeDefinition(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
placeholder
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("options=")
	builder.WriteString(fmt.Sprintf("%v", _m.Options))
	builder.WriteString(", ")
	builder.WriteString("required=")
	builder.WriteString(fmt.Sprintf("%v", _m.Required))
	builder.WriteString(", ")
	builder.WriteString("validation=")
	builder.WriteString(fmt.Sprintf("%v", _m.Validation))
	builder.WriteString(", ")
	builder.WriteString("placeholder=")
	builder.WriteString(_m.Placeholder)
	builder.WriteString(", ")
	builder.WriteString("display_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.DisplayOrder))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
placeholder

// UserAttributeDefinitions is a parsable slice of UserAttributeDefinition.
type UserAttributeDefinitions []*UserAttributeDefinition
